version: '3'

services:
  sql2017:
    image: nileshgule/sqldb
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    hostname: 'sql2017'
    container_name: sql2017
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    tty: true
  
  coremvc:
    image: nileshgule/coremvc
    container_name: coremvc
    build:
      context: ./CoreMVC
      dockerfile: Dockerfile
    depends_on: 
      - corewebapi
    ports:
      - "80:80"
      
  corewebapi:
    image: nileshgule/corewebapi
    container_name: corewebapi
    build:
      context: ./CoreWebAPI
      dockerfile: Dockerfile
    depends_on:
      - sql2017
    ports:
      - "8080:8080"

volumes:
  mssql-server-linux-data:

  
